version: '3.8'

services:
  backend:
    build:
      context: .
    env_file:
      - .env
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=development
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/app
    command: npm run start
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
